// utils.js
export const courseTags = [
  "Programming",
  "Data Science",
  "Machine Learning",
  "Artificial Intelligence",
  "Web Development",
  "Mobile Development",
  "Cloud Computing",
  "Cybersecurity",
  "Software Engineering",
  "Database Management",
  "DevOps",
  "UI/UX Design",
  "Game Development",
  "Blockchain",
  "Internet of Things (IoT)",
  "Big Data",
  "Business Analytics",
  "Project Management",
  "Digital Marketing",
  "Finance",
  "Entrepreneurship",
  "Leadership",
  "Communication Skills",
  "Creative Writing",
  "Graphic Design",
  "Photography",
  "Music Production",
  "Language Learning",
  "Mathematics",
  "Physics",
  "Biology",
  "Chemistry",
  "History",
  "Psychology",
  "Philosophy",
];
